#!/usr/bin/python3
#SPDX-FileCopyrightText: 2022 Noguchi Kousuke <s20C1093@s.chibakoudai.jp>
#SPDX-License-Identifier: BSD-3-Clause

import sys
import re

x = 0
for line in sys.stdin:
    try:
        x += int()
    except:
        x += float(n)

print(x)
